#!/bin/bash
# update-upstream.sh — Atualiza argenta-tui com upstream OpenCode
# Uso: ./scripts/update-upstream.sh [versão]
# Exemplo: ./scripts/update-upstream.sh v1.3.14

set -e

UPSTREAM_URL="https://github.com/anomalyco/opencode.git"
BRANCH_PREFIX="update/upstream"
TIMESTAMP=$(date +%Y%m%d-%H%M%S)

# Cores para output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}=== Argenta-Tui — Atualização Upstream ===${NC}"

# 1. Verificar se estamos no diretório correto
if [ ! -d ".git" ]; then
    echo -e "${RED}Erro: Execute este script a partir da raiz do repositório argenta-tui${NC}"
    exit 1
fi

# 2. Verificar se upstream existe
if ! git remote get-url upstream &>/dev/null; then
    echo -e "${YELLOW}Adicionando remote upstream...${NC}"
    git remote add upstream "$UPSTREAM_URL"
fi

# 3. Fetch upstream
echo -e "${GREEN}Buscando atualizações do upstream...${NC}"
git fetch upstream --tags

# 4. Determinar versão
VERSION=${1:-$(git describe --tags --abbrev=0 upstream/main 2>/dev/null || echo "latest")}
echo -e "${GREEN}Versão alvo: $VERSION${NC}"

# 5. Criar branch de atualização
BRANCH_NAME="${BRANCH_PREFIX}-${VERSION}-${TIMESTAMP}"
echo -e "${GREEN}Criando branch: $BRANCH_NAME${NC}"
git checkout -b "$BRANCH_NAME"

# 6. Merge seletivo (apenas código-fonte, não customizações)
echo -e "${YELLOW}Iniciando merge seletivo...${NC}"
echo -e "${YELLOW}IMPORTANTE: Resolva conflitos mantendo customizações Argenta:${NC}"
echo -e "${YELLOW}  - theme/argenta.json${NC}"
echo -e "${YELLOW}  - sidebar/footer.tsx${NC}"
echo -e "${YELLOW}  - tips-view.tsx${NC}"
echo -e "${YELLOW}  - dialog-status.tsx${NC}"
echo -e "${YELLOW}  - system prompts/*.txt${NC}"
echo ""

git merge "upstream/$VERSION" --no-commit --no-ff || {
    echo -e "${RED}Conflitos detectados. Resolva manualmente e execute:${NC}"
    echo -e "${RED}  git add . && git commit -m 'merge: upstream $VERSION'${NC}"
    exit 1
}

# 7. Regenerar models-snapshot.js
echo -e "${GREEN}Regenerando models-snapshot.js...${NC}"
cd packages/opencode
curl -s https://models.dev/api.json > /tmp/models-dev.json
cat > src/provider/models-snapshot.js << EOF
// @ts-nocheck
// Auto-generated by update-upstream.sh - do not edit
export const snapshot = $(cat /tmp/models-dev.json)
EOF
cd ../..

# 8. Compilar binário
echo -e "${GREEN}Compilando binário argenta-fenix...${NC}"
cd packages/opencode
bun run build --single
cd ../..

# 9. Verificar binário
BIN_PATH="packages/opencode/dist/argenta-fenix-$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m)/bin/argenta-fenix"
if [ -f "$BIN_PATH" ]; then
    echo -e "${GREEN}Binário gerado: $BIN_PATH${NC}"
    "$BIN_PATH" --version
else
    echo -e "${YELLOW}Binário não encontrado em $BIN_PATH${NC}"
    echo -e "${YELLOW}Verifique a pasta packages/opencode/dist/${NC}"
fi

# 10. Commit
echo -e "${GREEN}Commitando atualização...${NC}"
git add .
git commit -m "feat(tui): Atualização upstream $VERSION

- Merge seletivo com upstream OpenCode
- Customizações Argenta preservadas
- models-snapshot.js regenerado
- Binário argenta-fenix compilado"

echo -e "${GREEN}=== Atualização concluída! ===${NC}"
echo -e "${GREEN}Branch: $BRANCH_NAME${NC}"
echo -e "${GREEN}Para testar: cd packages/opencode && bun run dev${NC}"
echo -e "${GREEN}Para merge: git checkout dev && git merge $BRANCH_NAME${NC}"
